<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qualitygatemodel" nsURI="http://palladiosimulator.org/qualitygatemodel/1.0"
    nsPrefix="qualitygatemodel">
  <eClassifiers xsi:type="ecore:EClass" name="QualityGate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/PCMRandomVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" lowerBound="1" eType="#//Scope"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="impact" eType="#//Impact"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="criticality" eType="#//Criticality"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scope" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Impact"/>
  <eClassifiers xsi:type="ecore:EClass" name="Criticality"/>
  <eClassifiers xsi:type="ecore:EClass" name="SignatureScope" abstract="true" eSuperTypes="#//Scope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/Signature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetricScope" abstract="true" eSuperTypes="#//Scope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metric" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.palladiosimulator.metricspec/model/metricspec.ecore#//MetricDescription"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestParameterScope" eSuperTypes="#//SignatureScope"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResultParameterScope" eSuperTypes="#//SignatureScope"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequestMetricScope" eSuperTypes="#//MetricScope #//SignatureScope"/>
  <eClassifiers xsi:type="ecore:EClass" name="RessourceScope" eSuperTypes="#//MetricScope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourcetype" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourcetype/ResourceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventBasedCommunicationScope" eSuperTypes="#//RequestMetricScope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedrole" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/ProvidedRole"/>
  </eClassifiers>
</ecore:EPackage>
